services:
  preprocessing-service:
    build:
      context: .
      dockerfile: crates/preprocessing-service/Dockerfile.rust

  sentiment-service:
    build:
      context: .
      dockerfile: crates/sentiment-service/Dockerfile.rust

  storage-service:
    build:
      context: .
      dockerfile: crates/storage-service/Dockerfile.rust

  api-service:
    build:
      context: .
      dockerfile: crates/api-service/Dockerfile.rust
