FROM rust:latest as builder
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*
COPY . .
RUN cargo build --release --bin service-sentiment

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/app/target/release/service-sentiment /app/service-sentiment
COPY sentiment-service/model_quant /app/sentiment-service/model_quant
ENV MODEL_DIR=/app/sentiment-service/model_quant
CMD ["/app/service-sentiment"]
