CREATE TABLE IF NOT EXISTS posts (
    post_pk     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id          TEXT NOT NULL,
    symbol      TEXT NOT NULL DEFAULT 'UNKNOWN',
    platform    TEXT NOT NULL,
    text        TEXT NOT NULL,
    timestamp   TIMESTAMPTZ NOT NULL,
    sentiment   TEXT NOT NULL,
    scores      JSONB NOT NULL,
    topic_id    INTEGER,
    topic_label TEXT,
    scored_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    engagement  INTEGER NOT NULL DEFAULT 1
);

-- Migrate installations where a source-provided post ID was the primary key.
-- A source ID is only unique within its platform/symbol scope: one source post
-- can match multiple tracked symbols, and unrelated platforms can reuse IDs.
ALTER TABLE posts
    ADD COLUMN IF NOT EXISTS post_pk BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Preserve idempotent ingestion before removing the old global-id primary key.
CREATE UNIQUE INDEX IF NOT EXISTS posts_source_identity_uidx
    ON posts (platform, id, symbol);

DO $$
DECLARE
    current_primary_key TEXT;
    current_primary_key_columns TEXT[];
BEGIN
    SELECT
        constraint_info.conname,
        array_agg(attribute_info.attname ORDER BY key_info.ordinality)
    INTO current_primary_key, current_primary_key_columns
    FROM pg_constraint AS constraint_info
    CROSS JOIN LATERAL unnest(constraint_info.conkey)
        WITH ORDINALITY AS key_info(attnum, ordinality)
    JOIN pg_attribute AS attribute_info
      ON attribute_info.attrelid = constraint_info.conrelid
     AND attribute_info.attnum = key_info.attnum
    WHERE constraint_info.conrelid = 'posts'::regclass
      AND constraint_info.contype = 'p'
    GROUP BY constraint_info.conname;

    IF current_primary_key_columns IS DISTINCT FROM ARRAY['post_pk']::TEXT[] THEN
        IF current_primary_key IS NOT NULL THEN
            EXECUTE format(
                'ALTER TABLE posts DROP CONSTRAINT %I',
                current_primary_key
            );
        END IF;

        ALTER TABLE posts
            ADD CONSTRAINT posts_pkey PRIMARY KEY (post_pk);
    END IF;
END $$;

-- Ensure engagement column exists if database table already created.
ALTER TABLE posts ADD COLUMN IF NOT EXISTS engagement INTEGER NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS posts_symbol_idx ON posts (symbol);
CREATE INDEX IF NOT EXISTS posts_sentiment_idx ON posts (sentiment);
CREATE INDEX IF NOT EXISTS posts_platform_idx ON posts (platform);
CREATE INDEX IF NOT EXISTS posts_symbol_timestamp_idx ON posts (symbol, timestamp DESC);


CREATE TABLE IF NOT EXISTS tracked_symbols (
    symbol            TEXT PRIMARY KEY,
    keywords          JSONB NOT NULL DEFAULT '[]'::jsonb,
    future            TEXT,
    sector            TEXT,
    require_uppercase BOOLEAN NOT NULL DEFAULT FALSE,
    require_cashtag   BOOLEAN NOT NULL DEFAULT FALSE,
    block_phrases     JSONB NOT NULL DEFAULT '[]'::jsonb,
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ensure require_cashtag column exists if database table already created
ALTER TABLE tracked_symbols ADD COLUMN IF NOT EXISTS require_cashtag BOOLEAN NOT NULL DEFAULT FALSE;


CREATE TABLE IF NOT EXISTS stock_quotes (
    id          SERIAL PRIMARY KEY,
    symbol      TEXT NOT NULL,
    timestamp   TIMESTAMPTZ NOT NULL,
    price       FLOAT NOT NULL,
    volume      BIGINT NOT NULL,
    market_session TEXT NOT NULL DEFAULT 'closed',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (symbol, timestamp)
);

CREATE INDEX IF NOT EXISTS stock_quotes_symbol_idx ON stock_quotes (symbol);
CREATE INDEX IF NOT EXISTS stock_quotes_timestamp_idx ON stock_quotes (timestamp);
CREATE INDEX IF NOT EXISTS stock_quotes_symbol_timestamp_idx ON stock_quotes (symbol, timestamp DESC);
CREATE INDEX IF NOT EXISTS stock_quotes_symbol_session_timestamp_idx ON stock_quotes (symbol, market_session, timestamp DESC);

-- Older installations may predate quote identity enforcement. Only run the
-- duplicate cleanup while performing that one-time migration: once a matching
-- unique constraint exists, a table-wide self-join can never find duplicates
-- and would just add work and lock contention to every service startup.
DO $$
DECLARE
    has_quote_identity_constraint BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1
        FROM pg_constraint AS constraint_info
        WHERE constraint_info.conrelid = 'stock_quotes'::regclass
          AND constraint_info.contype = 'u'
          AND ARRAY(
              SELECT attribute_info.attname::TEXT
              FROM unnest(constraint_info.conkey)
                  WITH ORDINALITY AS key_info(attnum, ordinality)
              JOIN pg_attribute AS attribute_info
                ON attribute_info.attrelid = constraint_info.conrelid
               AND attribute_info.attnum = key_info.attnum
              ORDER BY key_info.ordinality
          ) = ARRAY['symbol', 'timestamp']::TEXT[]
    ) INTO has_quote_identity_constraint;

    IF NOT has_quote_identity_constraint THEN
        -- Keep a concurrent writer from recreating a duplicate between cleanup
        -- and constraint creation. This stronger lock is taken only once, on a
        -- legacy table that does not yet enforce quote identity.
        LOCK TABLE stock_quotes IN SHARE ROW EXCLUSIVE MODE;

        DELETE FROM stock_quotes AS older_quote
        USING stock_quotes AS newer_quote
        WHERE older_quote.id > newer_quote.id
          AND older_quote.symbol = newer_quote.symbol
          AND older_quote.timestamp = newer_quote.timestamp;

        ALTER TABLE stock_quotes
            ADD CONSTRAINT unique_symbol_timestamp
            UNIQUE (symbol, timestamp);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS stock_metrics (
    symbol                  TEXT PRIMARY KEY,
    pe_ratio                FLOAT,
    beta                    FLOAT,
    avg_return_1y           FLOAT,
    inflation_adj_return_1y FLOAT,
    pe_relative_sector      FLOAT,
    beta_relative_sector    FLOAT,
    return_relative_sector  FLOAT,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger to notify on new post inserts
CREATE OR REPLACE FUNCTION notify_new_post()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM pg_notify(
        'new_posts',
        json_build_object(
            'id', NEW.id,
            'symbol', NEW.symbol,
            'platform', NEW.platform,
            'text', left(NEW.text, 1000),
            'timestamp', NEW.timestamp,
            'sentiment', NEW.sentiment,
            'scores', NEW.scores,
            'topic_id', NEW.topic_id,
            'topic_label', NEW.topic_label,
            'scored_at', NEW.scored_at,
            'engagement', NEW.engagement
        )::text
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_notify_new_post
AFTER INSERT ON posts
FOR EACH ROW
EXECUTE FUNCTION notify_new_post();


-- Hourly aggregation table for cold-tier data retention. Expired raw posts are
-- deleted and aggregated from the same DELETE ... RETURNING statement so a row
-- cannot be pruned without its contribution being preserved here.
CREATE TABLE IF NOT EXISTS hourly_sentiment_agg (
    symbol              TEXT NOT NULL,
    bucket_hour         TIMESTAMPTZ NOT NULL,
    positive_count      INTEGER NOT NULL DEFAULT 0,
    neutral_count       INTEGER NOT NULL DEFAULT 0,
    negative_count      INTEGER NOT NULL DEFAULT 0,
    positive_weighted   FLOAT NOT NULL DEFAULT 0,
    negative_weighted   FLOAT NOT NULL DEFAULT 0,
    neutral_weighted    FLOAT NOT NULL DEFAULT 0,
    total_weighted      FLOAT NOT NULL DEFAULT 0,
    sentiment_index     FLOAT NOT NULL DEFAULT 0,
    PRIMARY KEY (symbol, bucket_hour)
);
