FROM rust:latest as builder
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y pkg-config libssl-dev ca-certificates curl && rm -rf /var/lib/apt/lists/*
ENV CARGO_BUILD_JOBS=1

COPY . .
RUN cargo build --release --bin service-preprocessing
RUN cp target/release/service-preprocessing /usr/src/app/service-preprocessing-bin

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/app/service-preprocessing-bin /app/service-preprocessing
COPY preprocessing-service/model_quant /app/preprocessing-service/model_quant
ENV MODEL_DIR=/app/preprocessing-service/model_quant
CMD ["/app/service-preprocessing"]
