[package]
name = "market-producer"
version = "0.1.0"
edition = "2021"

[lib]
name = "market_producer"

[[bin]]
name = "producer-market"
path = "src/main.rs"

[dependencies]
social-sentiment-core = { path = "../social-sentiment-core" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
chrono-tz = { workspace = true }

